Describe key optionality property of maps on the README.
Showmax/env pull request #14
Opened 2021-10-29 11:18 UTC by jan-dubsky

Closes #13

2021-10-29 16:26 UTC, Hrubon requested changes
Nice elaboration. But I am not sure whether it is desirable to have such elaboration present on "homepage" of the project. I would be for keeping the homepage as concise and readable as possible. This nicely explains the motivation and design choices, but it goes into detail just too much, in my opinion.

I would suggest putting this to the end of the [GitHub issue](https://github.com/Showmax/env/issues/13) as a conclusion. Or at least put it on a separate README page (not sure whether and how actually GitHub supports that). And write a **short** paragraph at the end of the [Parsing maps](https://github.com/Showmax/env/#parsing-maps) section on homepage, stating just something like: _"Beware of maps, they are implicitly optional. See this GitHub issue (or this page) for more details, reasons, and discussion."_

2021-10-31 09:54 UTC, jan-dubsky commented on README.md
> +would be able to express an empty map by an empty object. And we could `require`
I don't think so. The sentence would be weird then. I express something, not express something as something.

2021-10-31 09:56 UTC, jan-dubsky commented on README.md
> +the presence of the config file key even in case its content is empty. The same
"in case" in this case has the same meaning as "if" -> no "the"

2021-10-31 09:56 UTC, jan-dubsky commented on README.md
> +types (primitive types, arrays, `TextUnmershaler`), there exists a value of
`TextUnmarshaler` (single L) - See: https://pkg.go.dev/encoding#TextUnmarshaler

2021-10-31 09:58 UTC, jan-dubsky commented on README.md
> +where no environment variable with a given prefix are present. As parsing of an
> Also "parsing an empty map" (without "of") might be better?
I don't believe so. You have parsing **of** Latin, parsing **of** JSON, so here yo ushould have parsing **of** an empty map.

2021-11-01 13:09 UTC, jan-dubsky commented on README.md
> +While parsing maps we denote every map key by environment variable presence!
Rephrased. Thanks.

2021-11-02 16:21 UTC, Hrubon approved these changes
Approved. I have also added a headline that will emphasize the short-summary in section about maps.

2021-11-02 16:22 UTC, merged