Bugfix: Expansion of escape sequences had wrong priority
Showmax/env pull request #3
Opened 2020-11-05 17:13 UTC by Hrubon

Double bask-slashes should expand first, then the quotes. See the added example in tests.

2020-11-05 17:27 UTC, graywolf-at-work requested changes
I do not think this is correct.

2020-11-05 17:27 UTC, graywolf-at-work commented on env_test.go
> +		`"foo\\"`: {`foo\`},
Consider also adding test line

```
`foo \\\\ bar`: {`foo \\ bar`}
```

and see what breaks :)

2020-11-06 18:15 UTC, Hrubon commented
I refactored the slice parsing logic a little bit. However, I kept the two passes over the input (tokenization and expansion of escape sequences). I tried to implement it in one pass but it sucked in readability.

2020-11-12 13:00 UTC, graywolf-at-work requested changes
Looks good thx :)

Just few readability changes requested.

2020-11-12 13:58 UTC, merged